### ISSUE TITLE
Adicionar regex para horário nos formatos 12h e 24h

### ISSUE THREAD

**Issue by cleidson-os** [osintbrazuca/osint-brazuca-regex#13]
/(([0][1-9]|[1][0-2]):([0-5][0-9])([p][m]))|(([0][0-9]|[1][01]):([0-5][0-9])([a][m]))/ 12horas
/([01][0-9]|[2][0-3]):([0-5][0-9])/ 24horas

**Comment by MrCl0wnLab** [comment]
Vlw, assim que possível vamos adicionar.

**Comment by jgmarquesm** [comment]
Regex para formato 12h

((0?[1-9]|1[0-2]):([0-5][0-9].?([a].?[m].?|[p].?[m].?)))

A minha regex para 24 hr foi a mesma do amigo acima, mas como no formato 12h, meia noite é 12AM e não 00AM, cheguei nessa regex.

**Comment by MrCl0wnLab** [comment]
Olá @Cleidson-Oliveira e @jgmarquesm ,
Obrigado pela contribuição.
