### ISSUE TITLE
Adicionar regex para validação de senhas

### ISSUE THREAD

**Issue by jgmarquesm** [osintbrazuca/osint-brazuca-regex#16]
Solução: 

## Senha (8-20 digitos, letras maiúsculas, minuscúlas, números e caracteres especiais)

```
^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%&*!-+^&*]).{8,20}$
```

JSON:

"senha": [ { "regex": "(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%&*!-+^&*]).{8,20}", "description": "Validador de senhas com tamanho entre 8 e 20 digitos e com letras maiúsculas, minuscúlas, números e caracteres especiais"} ]

**Comment by MrCl0wnLab** [comment]
## Obrigado pela contribuição
Ref: https://github.com/osintbrazuca/osint-brazuca-regex/pull/21

**Comment by jgmarquesm** [comment]
@MrCl0wnLab vi que no readme eu deixei a versão mais antiga da regex. A do json está correta. Se quiser alterar é so copiar do json pro readme, para não precisar abrir um PR.
