### ISSUE TITLE
Melhoria no regex de Email

### ISSUE THREAD

**Issue by lucasdonordeste** [osintbrazuca/osint-brazuca-regex#26]
`"regex": "^([\w._%+-]+)@([\w.-]+)\.([\w]{2,})$"`

Este regex usa a classe de caracteres \w para corresponder a qualquer caractere alfanumérico ou sublinhado (_) em vez de escrever os caracteres permitidos explicitamente. Ele também usa os marcadores de posição ^ e $ para garantir que o padrão começa e termina na string inteira, respectivamente. Além disso, ele usa grupos de captura para permitir que você acesse as diferentes partes do endereço de e-mail separadamente.

**Comment by MrCl0wnLab** [comment]
Olá @lucasdonordeste ,
Agradeço pela contribuição .


REGEX ADICIONADA
- https://github.com/osintbrazuca/osint-brazuca-regex/commit/94e57b38041e1f271f019c2fe2316303585d6a49

O regex que você enviou é muito boa! adicionei um upgrade nela para detectar e-mails com **defang**

Exemplo:

```
dep.AAAA@camara.leg.br 
dep.BBBB[at]camara.leg.br
dep.CCCC at camara.leg.br
dep.XXXXX @ camara.leg.br
dep.OOOO@camara.intranet-leg.br
<a href="mail:dep.IIIII-123@camara.leg.br">teste</a>
<p>dep.123.WWWW@camara.leg.br</p>
```

![image](https://github.com/osintbrazuca/osint-brazuca-regex/assets/17049332/50cc8164-b781-4d2f-9341-1919b1bd708b)
