### ISSUE TITLE
Melhoria no regex do telefone

### ISSUE THREAD

**Issue by lucasdonordeste** [osintbrazuca/osint-brazuca-regex#27]
`"regex": "(?:(?:(\\+|00)?(55))\\s?)?(?:\\(?(\\d{2})\\)?\\s?)?(?:(9\\d|[2-9])\\d{3}\\-?(\\d{4}))"`

Este regex usa a classe de caracteres \d para corresponder a qualquer dígito de 0 a 9 e a classe de caracteres \s para corresponder a qualquer espaço em branco. Ele também usa grupos opcionais e grupos de captura para permitir que algumas partes do padrão sejam opcionais e para permitir que você acesse as diferentes partes do número de telefone separadamente.

**Comment by MrCl0wnLab** [comment]
Olá @lucasdonordeste ,
Obrigado pela REGEX,

REGEX ADICIONADA
- https://github.com/osintbrazuca/osint-brazuca-regex/commit/798f701666cbe81c167eec9c66bf9892f8cfdc1b

Dei uma melhorada.

Valores teste:
```
(81)38362900
(87)38218456
<a href='tel://8194882975'>(81) 9488 2975</a>
<p>11916083186</p>
11986183116
(11)998085116
(11) 996083516
(87)38552814
(87)37734908
(81) 8494.1509
(87)38355903
(81)38362900
(81)37354900
```


![image](https://github.com/osintbrazuca/osint-brazuca-regex/assets/17049332/c610c304-1bd8-45b3-af18-ce98e23ffe7f)
