### ISSUE TITLE
Adicionar Regex de nomes brasileiros

### ISSUE THREAD

**Issue by oicaroabreu** [osintbrazuca/osint-brazuca-regex#31]
Nomes completos como:
>Pedro de Alcântara João Carlos Leopoldo Salvador Bibiano Francisco Xavier de Paula Leocádio Miguel Gabriel Rafael Gonzaga

É sempre um sofrimento montar regex de nome brasileiro.

**Comment by MrCl0wnLab** [comment]
Olá @oicaroabreu ,

Obrigado pela contribuição, mas vamos recusar a regex.
Temos um foco mais em valores de track
exemplo:
- ips, documentos, pix.

Tentar detectar nomes Brasileiros pode gerar muito falso positivo.

Att
