### ISSUE TITLE
Adicionar sigla das UF`s

### ISSUE THREAD

**Issue by arthurfg** [osintbrazuca/osint-brazuca-regex#9]
Adicionar a regex para as siglas das UFs, algo simples como: `(AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO|BR)`

**Comment by MrCl0wnLab** [comment]
Obrigado pela contribuição :)

**Comment by arthurfg** [comment]
nada, se quiser posso abrir o PR. Mas fica a critério de vcs tb, não sei se querem adicionar algo.
